# Generated by Django 4.2.6 on 2023-10-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(
                choices=[
                    ("comedy", "Comedy"),
                    ("drama", "Drama"),
                    ("educational", "Educational"),
                    ("thriller", "Thriller"),
                ],
                default="None",
                max_length=50,
            ),
        ),
    ]
